CREATE TABLE `PERSON` (
  `ID` varchar(36) NOT NULL PRIMARY KEY,
  `NAME` varchar(100) NOT NULL,
  `PARENT_ID` varchar(100) NULL,
  `CREATED_D` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  `MODIFIED_D` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)
);

CREATE INDEX `PERSON_X1` ON `PERSON`(`PARENT_ID`);
