spring:
  application:
    name: queue-testing-poc
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: queue-testing-poc-kafka-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.gabrielspassos.*
            type:
              mapping: exchangeEvent:com.gabrielspassos.event.ExchangeEvent

exchange:
  api:
    url: https://cdn.jsdelivr.net