CREATE TABLE IF NOT EXISTS people (
id       VARCHAR(60)  PRIMARY KEY,
name     VARCHAR      NOT NULL
);

CREATE TABLE IF NOT EXISTS cars (
id       VARCHAR(60)  DEFAULT RANDOM_UUID() PRIMARY KEY,
model    VARCHAR      NOT NULL
);